version: '3.4'

services:
  bliss.recruitment:
    image: ${DOCKER_REGISTRY-}blissrecruitment
    build:
      context: .
      dockerfile: Bliss.Recruitment/Dockerfile

  db.bliss.recruitment:
    image: mcr.microsoft.com/mssql/server:2017-latest
